### ISSUE TITLE
CSS 클래스명 변경

### ISSUE THREAD

**Issue by simonseo** [osamhack2021/ai_web_RISKOUT_BTS#79]
`/workspaces/ai_web_RISKOUT_BTS/WEB/frontend/src/css/SideNavigation.css`
```css
.css-i4bv87-MuiSvgIcon-root {
  /*햄버거 버튼 크기*/
  width: 1.5em;
}
```

`i4bv87` 같은 부분은 자동으로 생성해주는 클래스라서 빌드할 때 클래스명이 바뀔 수 있습니다.
자동 생성된 클래스명 말고 직접 지정해서 CSS 적용해주세요!
